# Generated by Django 4.1.4 on 2023-02-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_crypto_price10_crypto_price7_crypto_price8_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='price11',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto',
            name='price12',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
