# Generated by Django 4.1.4 on 2023-02-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_crypto_price11_crypto_price12'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='price13',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
